
GET http://localhost:1337/employees


### 

POST http://localhost:1337/hiring-requests
Content-Type: application/json

{
    "firstName": "Jenny",
    "lastName": "Cooper",
    "homeEmail": "jenny@aol.com",
    "homePhone": "867-5309",
    "requestedDepartment": "DEV",
    "requiredSalary": 80000
}